menu:
- {name: 'Research', url: '/research'}
- {name: 'Publications', url: '/publications'}
- {name: 'Team', url: '/team'}
- {name: 'Join', url: '/join'}

# - {name: 'Resources', url: '/resources'}
# - {name: 'Contact', url: '/contact'}
# - {name: 'Join', url: '/join'}

people:
- {name: 'Preeya Khanna', degrees: ', PhD', 
   position: 'Principal Investigator',
   extra_text: 'CV: ', 
   extra_link: 'team/preeya_cv.pdf', extra_link_text: 'link',
   image: 'assets/img/preeya.jpg'} 
  
  # title: 'Assistant to the Professor', 
  # department: 'Electrical Engineering & Computer Sciences', 
  # institution: 'Helen Wills Neuroscience Institute', 
  # email: 'pkhanna at berkeley dot edu'}

- {name: 'You?', degrees: '', 
  position: ' ', 
  extra_text: ' Check out the "join" tab for opportunities to get involved!',
  image: 'assets/img/you.jpg', url: ''}

social:
- {icon: 'github', link: 'https://github.com/neuralengatberkeley'}
- {icon: 'twitter', link: 'https://twitter.com/prekhanna'}

contacts:
- {name: 'Preeya Khanna', title: 'Assistant Professor', department: '', institution: 'Electrical Engineering & Computer Sciences', institution_address: 'Helen Wills Neuroscience Institute', phone: '', email: 'pkhanna at berkeley dot edu', office: '', image: 'assets/img/contact.jpg'}
