menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'team', url: '/team'}
- {name: 'resources', url: '/resources'}
- {name: 'contact', url: '/contact'}
- {name: 'join', url: '/join'}

people:
- {name: 'Preeya Khanna', title: 'Assistant Professor', department: 'Electrical Engineering & Computer Sciences', institution: 'Helen Wills Neuroscience Institute', institution_address: '', phone: '', email: 'pkhanna at berkeley dot edu', office: '', image: 'assets/img/primary-investigator.jpg', url: 'preeya'}
- {name: 'You?', title: '', department: '', institution: '', institution_address: '', phone: '', email: '', office: '', image: 'assets/img/lab-technician.jpg', url: 'you'}

social:
- {icon: 'github', link: 'https://github.com/neuralengatberkeley'}
- {icon: 'twitter', link: 'https://twitter.com/prekhanna'}

contacts:
- {name: 'Preeya Khanna', title: 'Assistant Professor', department: 'Electrical Engineering & Computer Sciences', institution: 'Helen Wills Neuroscience Institute', institution_address: '', phone: '', email: 'pkhanna at berkeley dot edu', office: '', image: 'assets/img/contact.jpg'}
