menu:
- {name: 'Research', url: '/research'}
- {name: 'Publications', url: '/publications'}
- {name: 'Team', url: '/team'}
- {name: 'News', url: '/news'}
- {name: 'Join', url: '/join'}
- {name: 'Participate', url: '/participate'}

# - {name: 'Resources', url: '/resources'}
# - {name: 'Contact', url: '/contact'}
# - {name: 'Join', url: '/join'}

people:
- {name: 'Preeya Khanna', degrees: ', PhD', 
   position: 'Principal Investigator',
   extra_text: 'CV: ', 
   extra_link: 'team/preeya_cv.pdf', extra_link_text: 'link',
   image: 'assets/img/preeya.jpg'} 
  
  # title: 'Assistant to the Professor', 
  # department: 'Electrical Engineering & Computer Sciences', 
  # institution: 'Helen Wills Neuroscience Institute', 
  # email: 'pkhanna at berkeley dot edu'}
- {name: 'Woohyun Kim', degrees: ', PhD', 
   position: 'Postdoctoral researcher',
   extra_text: 'CV: ', 
   extra_link: 'team/Woohyun Kim_CV.docx .pdf', extra_link_text: 'link',
   image: 'assets/img/Woohyun Kim_lab website photo.jpg'} 

- {name: 'Shivam Chaudhary', degrees: ', BSc, MSc', 
   position: 'Research engineer',
   extra_text2: 'Personal website: ', 
   extra_link2: 'http://www.shivamc.com/', extra_link_text2: 'link',
   image: 'assets/img/ShivamLabWebsite.jpg'} 

- {name: 'Vidhi Sinha', degrees: ', BSc', 
   position: 'Neuroscience graduate student',
   extra_text2: '', 
   extra_link2: '', extra_link_text2: '',
   image: 'assets/img/vidhi.png'} 

- {name: 'Tom Oppenheim', degrees: ', PhD', 
   position: 'Visiting scholar',
   extra_text: 'CV: ', 
   extra_link: 'team/TomCV New.pdf', extra_link_text: 'link',
   image: 'assets/img/tom_image v3.png'} 

- {name: 'Yash Kodali', degrees: '', 
   position: 'Undergrad student researcher',
   extra_text2: 'Personal website: ', 
   extra_link2: 'https://yashck.github.io/', extra_link_text2: 'link',
   image: 'assets/img/yash_profile_picture.png'} 

- {name: 'Phil Xie', degrees: '', 
   position: 'Undergrad student researcher',
   extra_text2: 'Personal website: ', 
   extra_link2: 'https://www.linkedin.com/in/phil-xie/', extra_link_text2: 'link',
   image: 'assets/img/phil.png'} 

- {name: 'Zeyad Khokhar', degrees: '', 
   position: 'Undergrad student researcher',
   extra_text2: 'Personal website: ', 
   extra_link2: 'https://www.linkedin.com/in/zeyad-khokhar/', extra_link_text2: 'link',
   image: 'assets/img/zeyad.jpg'} 


- {name: 'You?', degrees: '', 
  position: ' ', 
  extra_text: ' Check out the "join" tab for opportunities to get involved!',
  image: 'assets/img/you.jpg', url: ''}

alumni:
- {name: 'Reece Huff', degrees: ', BSc, MSc', 
   position: 'Graduate student',
   extra_text2: 'Personal website: ', 
   extra_link2: 'https://reecehuff.com/', extra_link_text2: 'link',
   image: 'assets/img/reece_profile.png',
   role: 'graduate rotation student', 
   duration: July - Sept 2023,
   next: PhD in Machine learning @ UC Berkeley } 


social:
- {icon: 'github', link: 'https://github.com/neuralengatberkeley'}
- {icon: 'twitter', link: 'https://twitter.com/prekhanna'}

contacts:
- {name: 'Preeya Khanna', title: 'Assistant Professor', department: '', 
  institution: 'Electrical Engineering & Computer Sciences', institution_address: 'Helen Wills Neuroscience Institute', 
  phone: '', email: 'pkhanna at berkeley dot edu', office: '', image: 'assets/img/contact.jpg'}

newsreel: # no apostrophe's in description allowed
- {date: 'June  2024', description: 'Welcome summer undergrads Yash, Zeyad, Phil and research scholar Tom! ', image: 'assets/img/newsreel/join.jpg'}
- {date: 'May 21, 2024', description: 'The lab receives a seed grant from the Brain Research Foundation. Thanks BRF!', image: 'assets/img/newsreel/2024_brf.jpeg'}
- {date: 'May 2, 2024', description: 'Vidhi joins the lab -- welcome Vidhi! ', image: 'assets/img/newsreel/2024_vidhi_joins.jpg'}
- {date: 'April 9, 2024', description: 'Lab lunch in the sun :) ', image: 'assets/img/newsreel/2024_lablunch.jpg'}
- {date: 'April 1, 2024', description: 'The lab receives the R00 part of the NIH BRAIN initiative K99/R00!', image: 'assets/img/newsreel/2024_brainr00.png'}
- {date: 'March 29, 2024', description: 'The lab receives a Google Research Scholar award. Thanks Google!', image: 'assets/img/newsreel/2024_google.jpg'}
#- {date: 'March 26, 2024', description: 'Tommy starts his rotation in the lab -- welcome Tommy!', image: 'assets/img/newsreel/join.jpg'}
- {date: 'Feb 20, 2024', description: 'Preeya is named a 2024 Sloan Research Fellow. Thanks to the Alfred P. Sloan foundation for supporting our work!', image: 'assets/img/newsreel/2024_sloan.jpg'}  
- {date: 'Feb 19, 2024', description: 'First lab baby born and she is a thinker', image: 'assets/img/newsreel/2024_mayuri.jpg'}
- {date: 'Dec 14, 2023', description: 'Lab dinner at Viks Chaat in Berkeley!', image: 'assets/img/newsreel/2023_viks.jpg'}
#- {date: 'Nov 27, 2023', description: 'Vidhi starts her rotation in the lab -- welcome Vidhi!', image: 'assets/img/newsreel/join.jpg'}
- {date: 'Nov 14, 2023', description: 'Preeya and Behrazs work on coordinated cortical-subcortical beta burst dynamcis during recovery from stroke is presented at SFN 2023', image: 'assets/img/newsreel/2023_sfn.jpg'}
- {date: 'Oct 7, 2023', description: 'First lab hike in Tilden park, followed by lunch @ Cheeseboard !', image: 'assets/img/newsreel/2023_labhike.jpg'}
- {date: 'Oct 2, 2023', description: 'Woohyuns first day in the lab -- welcome Woohyun!', image: 'assets/img/newsreel/join.jpg'}
- {date: 'Sept 20, 2023', description: 'Preeya wins the Young Investigator Award and gives a talk at the SimCo conference in Chicago. Thanks for the support and the opportunity to speak, SimCo!', image: 'assets/img/newsreel/2023_SimianCollective.jpg'}
- {date: 'Sept 14, 2023', description: 'Our first lab meeting!', image: 'assets/img/newsreel/2023_labmeeting.jpg'}
- {date: 'Sept 12, 2023', description: 'Shivams first day in the lab -- welcome Shivam!', image: 'assets/img/newsreel/2023_shivam_day1.jpg'}
- {date: 'July 26, 2023', description: 'We win a UC Berkeley Spark Grant to support our project on hand kinematics! Thanks for the support, Berkeley', image: 'assets/img/newsreel/2023_uc_berkeley_seal.jpg'}
- {date: 'July 14, 2023', description: 'Reece starts his rotation in the lab -- welcome Reece!', image: 'assets/img/newsreel/join.jpg'}
- {date: 'July 3, 2023', description: 'The Sensorimotor Neural Engineering lab opens its doors at UC Berkeley!', image: 'assets/img/newsreel/2023_labopen.jpg'}
- {date: 'July 3, 2023', description: 'Preeya and Viveks BMI dynamics paper comes out in Current Biology!', image: 'assets/img/newsreel/2023_currbio.jpg'}
- {date: 'June 9, 2023', description: 'Preeya and Toms hand kinematics paper comes out in Neurorehabilitation and Neural Repair!', image: 'assets/img/newsreel/2023_nnr.jpg'}